import sys
from setuptools import setup, find_packages

from utilitiespackage.settings import VERSION, MINIMUM_PYTHON_VERSION

assert sys.version_info >= MINIMUM_PYTHON_VERSION

setup(
    name="utilities-package",
    version=VERSION,
    description="utilities package",
    url="https://gitlab.com/terminallabs/utilitiespackage/utilities-package",
    author="Terminal Labs",
    author_email="solutions@terminallabs.com",
    license="see LICENSE file",
    packages=find_packages(),
    zip_safe=False,
    include_package_data=True,
    install_requires=[
        "setuptools",
        "boltons",
        "utilitybelt",
        "numpy",
        "algorithms",
        "path.py",
        "bash",
        "sh",
        "configparser",
        "unidecode",
        "PyYAML",
        "ruamel.yaml",
        "toml",
        "simplejson",
        "tailer",
        "pytz",
        "termcolor",
        "texttable",
        "click",
        "typer",
        "schedule",
        "python-dateutil",
        "beautifulsoup4",
        "cssutils",
        "istr",
        "shortuuid",
        "hashids",
        "base58",
        "bcrypt",
        "aiohttp",
        "uritools",
        "sqlalchemy",
        "montydb",
        "requests",
        "falcon",
        "tornado",
        "cherrypy",
        "bottle",
        "flask",
        "fastapi",
        "Jinja2",
        "Genshi",
        "Mako",
        "Pillow",
        "coverage",
        "pycontracts",
        "pytest",
        "pytest-cov",
        "pytest-mock",
        "pytest-click",
        "pytest-pylint",
        "pytest-httpserver",
        "black",
        "flake8",
        "radon",
        "cli-passthrough",
    ],
    entry_points="""
        [console_scripts]
        utilitiespackage=utilitiespackage.__main__:main
    """,
)
