renamedirs = [ "[repo]/src/factory",]
editlines = []
inherited = [
".github/workflows/build.yml",
"src/factory/settings.py",
"src/factory/config.py",
"src/factory/utils.py",
"src/factory/core.py",
"LICENSE",
"MANIFEST.in",
".gitignore",
"poetry.toml",
]
semiinherited = [
"Makefile",
"pyproject.toml",
"setup.cfg",
"setup.py",
"Taskfile.yml",
]
